functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о них
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность оформить заказ и перейти на страницу оплаты

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию (адаптивная верстка)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах

implicit:
  - Корзина должна сохраняться в сессии браузера, чтобы товары не исчезали при перезагрузке страницы
  - Приложение должно быть SPA (без перезагрузки страниц при навигации)
  - Сайт должен поддерживать локализацию (перевод интерфейса на русский и английский)
  - Пользователь должен иметь возможность переключать язык интерфейса

